pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE     = "day5-nginx-app"
        DOCKER_CONTAINER = "day5-nginx"
        APP_PORT         = "80"
        TF_DIR            = "terraform/day5/env/dev"

    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Docker Build') {
            steps {
                dir('docker/day5-app') {
                    sh "docker build -t $DOCKER_IMAGE:latest ."
                }
            }
        }

        stage('Docker Test') {
            steps('Test Docker Container') {
                sh '''
                    docker rm -f $DOCKER_CONTAINER || true
                    docker run -d -p $APP_PORT:80 --name $DOCKER_CONTAINER $DOCKER_IMAGE:latest
                    sleep 5
                    curl -f http://localhost:$APP_PORT || exit 1
                '''
            }
        }

        stage('Terraform Init') {
            steps {
                dir("$TF_DIR") {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Format') {
            steps {
                dir("$TF_DIR") {
                    sh 'terraform fmt -check -recursive'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir("$TF_DIR") {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir("$TF_DIR") {
                    sh 'terraform plan -out=tfplan'
                }
            }
        }

        stage('Terraform Aprove and Apply') {
            steps {
                script {
                    input(
                        message: 'Do you want to run terraform apply?',
                        ok: 'Approve'
                    )
                }
                dir("${TF_DIR}") {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

    }

     post {
        success {
            echo 'Day 5 pipeline completed successfully.'
        }

        failure {
            echo 'Day 5 pipeline failed.'
        }

        always {
            sh 'docker rm -f $DOCKER_CONTAINER || true'
        }
    }
}